#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not found."
if [ ! -f "$PYFILE" ]; then
    echo "Error: Python file '$PYFILE' not found."
    exit 1
python3 ./$PYFILE
